<a href="https://colab.research.google.com/github/samsyano/Microsoft-Capstone-AI-Challenge/blob/master/Appliance_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://mpp0xc0ae45ef.blob.core.windows.net/drivendata-mpp-storage/data/19/public/data-release.zip

!unzip -o data-release.zip

--2019-12-28 12:31:57--  https://mpp0xc0ae45ef.blob.core.windows.net/drivendata-mpp-storage/data/19/public/data-release.zip
Resolving mpp0xc0ae45ef.blob.core.windows.net (mpp0xc0ae45ef.blob.core.windows.net)... 52.239.154.100
Connecting to mpp0xc0ae45ef.blob.core.windows.net (mpp0xc0ae45ef.blob.core.windows.net)|52.239.154.100|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30080041 (29M) [application/zip]
Saving to: ‘data-release.zip’

data-release.zip    100%[===================>]  28.69M  37.9MB/s    in 0.8s    

2019-12-28 12:31:58 (37.9 MB/s) - ‘data-release.zip’ saved [30080041/30080041]

Archive:  data-release.zip
  inflating: train_labels.csv        
   creating: test/
  inflating: test/1677_v.png         
  inflating: test/1795_c.png         
  inflating: test/1632_v.png         
  inflating: test/1919_v.png         
  inflating: test/1806_c.png         
  inflating: test/1576_v.png         
  inflating: test/1843_c.png         
  inflating: test/1768

In [18]:


from __future__ import print_function
import os
from PIL import Image
import pandas as pd
import keras
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K

import numpy.random as nr
from tensorflow import set_random_seed
import matplotlib.pyplot as plt
from keras.datasets import mnist
import keras.utils.np_utils as ku
import keras.models as models
import keras.layers as layers
from keras import regularizers

from keras.optimizers import rmsprop, Adam
from keras import backend as K

from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense


from keras.models import Sequential
from keras.layers import Dense, Activation

%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import image as mp_image

from skimage import io as sk_io
from skimage.color import rgb2gray
from skimage.transform import rescale, resize, downscale_local_mean




src_folder = './data'
train_folder = 'train/'
test_folder = 'test/'
# train_labels_path = './data/train_labels.csv'

test_images = []

test_images_c = []

valid_images = '_v.png'
valid_images_c = '_c.png'


train_data = pd.read_csv('train_labels.csv',index_col=0)

train_images = []
train_images_c = []


as_gray = True
in_channel = 4

if as_gray:
  in_channel = 1
img_rows, img_cols = 128, 176


# def Loading_images(train_folder, images, ext):
#     for filename in os.listdir(train_folder):
        
#         path = os.path.join(train_folder, filename)

#         img_gray = sk_io.imread(path, as_gray=True)
# #     
#         if img_gray is not None:
# #             img_gray= rgb2gray(img_gray)
#             if path.lower().endswith(ext):
#                 continue
#             images.append(img_gray)
# #             if path.lower().endswith(valid_images_c):
# # #                 continue
# #                 images.append(img_gray)
#     return images
       

# Loading_images(test_folder, test_images, valid_images)
# Loading_images(train_folder, train_images, valid_images)

# Loading_images(test_folder, test_images_c, valid_images_c)
# Loading_images(train_folder, train_images_c, valid_images_c)

# sorted(train_images, key=lambda id: f'train/{id}_v.png')
# sorted(train_images_c, key=lambda id: f'train/{id}_c.png')

# sorted(train_images, key=lambda id: f'train/{id}_v.png')
# sorted(train_images_c, key=lambda id: f'train/{id}_c.png')

def read_spectograms(file_paths, img_rows, img_cols, as_gray, channels):
  
  images = []
  
  for file_path in file_paths:
    images.append(sk_io.imread(file_path, as_grey = as_gray))
  
  images = np.asarray(images, dtype=np.float32)
  
  # normalize
  images = images / 255.0 #np.max(images)
  
  # reshape to match Keras expectaions
  images = images.reshape(images.shape[0], img_rows, img_cols, channels)

  return images


# def image2array(image):

#   image =  np.asarray(image)

#   return image


print(len(test_images_c))
print(len(train_images_c))

print(len(test_images))
print(len(train_images))








train_data.head(1500)

# plt.imshow(train_images[10])
# plt.imshow(train_images_c[10])

0
0
0
0


appliance
id             
1000          4
1001          9
1002          4
1003          9
1004          6
...         ...
1571          3
1572          3
1573          7
1574          3
1575          1

[576 rows x 1 columns]

In [20]:
train_data['current_file'] = train_data.index.map(lambda id: f'train/{id}_c.png')
train_data['voltage_file'] = train_data.index.map(lambda id: f'train/{id}_v.png')

print(train_data.head())

      appliance      current_file      voltage_file
id                                                 
1000          4  train/1000_c.png  train/1000_v.png
1001          9  train/1001_c.png  train/1001_v.png
1002          4  train/1002_c.png  train/1002_v.png
1003          9  train/1003_c.png  train/1003_v.png
1004          6  train/1004_c.png  train/1004_v.png


In [0]:
# print(test_images.shape)
# def imageReshape(train_images, train_images.shape[0], img_rows, img_cols):
#   train_images = train_images.reshape((train_images.shape[0], img_rows, img_cols, 1)).astype('float')/255
#   print(train_images.shape)
#   print(train_images.dtype)




In [12]:
train_data.shape

(576, 3)

In [21]:
# current files
train_images = read_spectograms(train_data.current_file.values, img_rows, img_cols, as_gray, in_channel)

# voltage files
train_images_c = read_spectograms(train_data.voltage_file.values, img_rows, img_cols, as_gray, in_channel)


/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:48: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')


In [23]:
num_classes = 11

train_labels = train_data['appliance']
# print(train_labels)
train_labels.shape


(576,)

In [24]:
train_labels = ku.to_categorical(train_labels, num_classes)

print(train_labels)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [0]:
from sklearn.model_selection import train_test_split

c_v_train_stack = np.stack((train_images_c, train_images), axis=4)

x_train, x_test, y_train, y_test = train_test_split(c_v_train_stack, train_labels, test_size = 0.25, random_state=666)

x_train_current = x_train[:,:,:,:,0]
x_test_current = x_test[:,:,:,:,0]

x_train_voltage = x_train[:,:,:,:,1]
x_test_voltage = x_test[:,:,:,:,1]


In [27]:
# defining the keras neural network
from keras.layers import Dense, Activation, Dropout, Flatten, Input, concatenate
from keras.layers.advanced_activations import LeakyReLU

batch_size = 128



# Training the multichannel CNN
input_v = Input(shape=(128,176, 1))
input_c = Input(shape=(128,176, 1))

input_shape =(128, 176, 1)

def createModel(input):
    
    conv_1 = Conv2D(32, (3,3), padding= 'same', activation='relu', input_shape=input_shape)(input)
    batch_1 = BatchNormalization(axis=-1)(conv_1)
    maxPool_1 = MaxPooling2D(pool_size=(2,2))(batch_1)
    maxPool_1 = Dropout(0.5)(maxPool_1)
    
    conv2_1 = Conv2D(64, (3, 3), padding='same', activation = 'relu')(maxPool_1)
    batch2_1 = BatchNormalization(axis=-1)(conv2_1)
    maxPool2_1 = MaxPooling2D(pool_size=(2,2))(batch2_1)
    maxPool2_1 = Dropout(0.3)(maxPool2_1)
    
    conv3_1 = Conv2D(128, (3,3), padding='same', activation = 'relu')(maxPool2_1)
    batch3_1 = BatchNormalization(axis=-1)(conv3_1)
    maxPool3_1 = MaxPooling2D(pool_size=(2,2))(batch3_1)
    maxPool3_1 = Dropout(0.5)(maxPool3_1)
   
    
    
    return maxPool3_1





In [28]:
current_input = Input(shape=input_shape)


voltage_input = Input(shape=input_shape)




current_model = createModel(current_input)

voltage_model = createModel(voltage_input)

conv_net = concatenate([current_model, voltage_model])

conv_net = Flatten()(conv_net)



from keras.models import Model



dense_out = Dense(1024, activation='relu')(conv_net)
dropOut = Dropout(0.25)(dense_out)
dense_out1 = Dense(124, activation='relu')(conv_net)
dropOut = Dropout(0.3)(dense_out1)
output = Dense(num_classes, activation='softmax')(dropOut)

model = Model([current_input, voltage_input], outputs=[output])







                
## Compile the model
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', 
                metrics = ['accuracy'])
# nn.compile(optimizer='rmsprop', loss='categorical_crossentropy', metric=['accuracy'])

## Now fit the model
# nr.seed(2356)
# set_random_seed(2333)

model.summary()












Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_3 (InputLayer)            (None, 128, 176, 1)  0                                            
__________________________________________________________________________________________________
input_4 (InputLayer)            (None, 128, 176, 1)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 128, 176, 32) 320         input_3[0][0]                    
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 128, 176, 32) 320        

In [0]:
from keras.callbacks import ModelCheckpoint
## Set up and call-backs for early stopping
filepath = 'my_model_file.hdf5' # define where the model is saved
callbacks_list = [
#         keras.callbacks.EarlyStopping(
#             monitor = 'val_loss', # Use accuracy to monitor the model
#             patience = 1 # Stop after one step with lower accuracy
#         ),
        keras.callbacks.ModelCheckpoint(
            filepath = filepath, # file where the checkpoint is saved
            monitor = 'val_acc', # Don't overwrite the saved model unless val_loss is worse
            save_best_only = True, # Only save model if it is the best
            mode='max'
        )
]




# history = model.fit([train_images, train_images_c], train_labels, validation_split=0.2, batch_size = 32, epochs = 4, verbose =1)        



In [30]:

history = model.fit([x_train_current, x_train_voltage], y_train,
          batch_size=64,
          epochs=20,
          callbacks=callbacks_list,
          verbose=1,
          validation_data=([x_test_current, x_test_voltage], y_test),
          shuffle=True)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Train on 432 samples, validate on 144 samples
Epoch 1/20
432/432 [==============================] - 75s 174ms/step - loss: 10.3606 - acc: 0.2153 - val_loss: 12.8721 - val_acc: 0.2014
Epoch 2/20
432/432 [==============================] - 70s 163ms/step - loss: 11.2516 - acc: 0.2986 - val_loss: 12.8721 - val_acc: 0.2014
Epoch 3/20
432/432 [==============================] - 70s 162ms/step - loss: 11.1001 - acc: 0.3079 - val_loss: 13.7092 - val_acc: 0.1181
Epoch 4/20
432/432 [==============================] - 70s 162ms/step - loss: 10.8711 - acc: 0.3125 - val_loss: 12.8721 - val_acc: 0.2014
Epoch 5/20
432/432 [==============================] - 70s 162ms/step - loss: 10.8694 - acc: 0.3241 - val_loss: 12.8721 - val_acc: 0.2014
Epoch 6/20
432/432 [==============================] - 70s 161ms/step - loss: 10.9353 - acc: 0.3194 - val_loss: 12.8721 - val_acc: 0.2014
Epoch 7/20
432/432 [================

In [31]:
# load weights
model.load_weights(filepath)

final_loss, final_acc = model.evaluate([x_test_current, x_test_voltage], y_test, verbose=1)
print("Final loss: {0:.6f}, final accuracy: {1:.6f}".format(final_loss, final_acc))

144/144 [==============================] - 7s 50ms/step
Final loss: 12.872090, final accuracy: 0.201389


In [32]:
predict_df = pd.read_csv('submission_format.csv', index_col=0)

predict_df['current_file'] = predict_df.index.map(lambda id: f'test/{id}_c.png')
predict_df['voltage_file'] = predict_df.index.map(lambda id: f'test/{id}_v.png')

test_images_c = read_spectograms(predict_df.current_file.values, img_rows, img_cols, as_gray, in_channel)
test_images = read_spectograms(predict_df.voltage_file.values, img_rows, img_cols, as_gray, in_channel)


#get the predictions for the test data
predicted_classes = model.predict([test_images, test_images_c])

predict_df['appliance'] = np.argmax(predicted_classes,axis=1)


predict_df.to_csv('submission.csv')



/usr/local/lib/python3.6/dist-packages/skimage/io/_io.py:48: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')


In [0]:
def plot_loss(history):
    '''Function to plot the loss vs. epoch'''
    train_loss = history.history['loss']
    test_loss = history.history['val_loss']
    x = list(range(1, len(test_loss) + 1))
    plt.plot(x, test_loss, color = 'red', label = 'Test loss')
    plt.plot(x, train_loss, label = 'Training losss')
    plt.legend()
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Loss vs. Epoch')
    
# plot_loss(history)  

In [0]:
def plot_accuracy(history):
    train_acc = history.history['acc']
    test_acc = history.history['val_acc']
    x = list(range(1, len(test_acc) + 1))
    plt.plot(x, test_acc, color = 'red', label = 'Test accuracy')
    plt.plot(x, train_acc, label = 'Training accuracy')
    plt.legend()
    plt.xlabel('Epoch')
    plt.ylabel('Accuracy')
    plt.title('Accuracy vs. Epoch')  
    
# plot_accuracy(history)   
